#!/bin/bash

complete -p declare >/dev/null 2>&1 && return

_declare_complete() {
    local i
    for ((i=COMP_CWORD-1;i>0;--i)); do
        case ${COMP_WORDS[i]} in
            '>')
                # switch to default completion for cases like
                # declare -p foo bar > ./<tab>
                compopt -o default -o bashdefault
                return
            ;;
            -[fF])
                mapfile -t COMPREPLY < <(compgen -A function "$2")
                return
            ;;
            -[lnprux])
                mapfile -t COMPREPLY < <(compgen -A variable "$2")
                return
            ;;
        esac
    done
}

complete -F _declare_complete declare
